#!/usr/bin/env bash
#
# One-click repository cleanup.
#
#   bash site/tools/clean.sh
#
# Removes regenerable build output, caches, OS noise and disposable backups so the
# repo stays lightweight. Everything deleted here is either rebuilt by Jekyll, fetched
# by Bundler, or a throwaway backup — your content, source and media are never touched.
# After running this you can safely `git add -A && git commit && git push`; the GitHub
# Actions workflow rebuilds the site and Pages serves it correctly.

set -euo pipefail

# Resolve repo root from this script's location (works from any CWD).
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

removed=0
zap() { # zap <description> <find-args...>
  local desc="$1"; shift
  local hits
  hits="$(find . -path ./.git -prune -o \( "$@" \) -print 2>/dev/null || true)"
  if [ -n "$hits" ]; then
    echo "  • $desc"
    while IFS= read -r p; do [ -n "$p" ] && rm -rf "$p" && removed=$((removed + 1)); done <<<"$hits"
  fi
}

echo "Cleaning $ROOT ..."

# Jekyll build output & caches (regenerated by `jekyll build`)
zap "Jekyll build output / caches" \
  \( -name "_site" -o -name ".jekyll-cache" -o -name ".sass-cache" -o -name ".jekyll-metadata" \) -type d -o -name ".jekyll-metadata" -type f

# Ruby / Bundler install dirs (restored by `bundle install`)
zap "Bundler vendor / .bundle dirs" \
  \( -name "vendor" -o -name ".bundle" \) -type d

# Disposable media backups left by tools/convert_videos.sh
zap "Video backups (*_bk.*)" \
  -type f \( -name "*_bk.mp4" -o -name "*_bk.mov" -o -name "*_bk.webm" -o -name "*_bk.m4v" \)

# Python tooling junk
zap "Python caches" \
  \( -name "__pycache__" -type d -o -name "*.pyc" -type f \)

# OS / editor noise
zap "OS & editor noise" \
  -type f \( -name ".DS_Store" -o -name "Thumbs.db" -o -name "*.swp" -o -name "*~" \)

# Stray logs
zap "Log files" \
  -type f \( -name "*.log" -o -name "log.txt" \)

echo "Done. Removed $removed item(s)."
echo "Local-only tooling (e.g. site/assets/media/blog/script) is git-ignored and will not be uploaded."
